### ISSUE TITLE
connect: Connection refused

### ISSUE THREAD

**Issue by benoliver999** [LemonBoy/ldm#46]
Every so often, ldm starts spitting out an error (via `ldmc`):

    connect: Connection refused

This happens with both options, `-l` and `-r`. ldm also stops mounting devices.

I'm running ldm on Arch via systemd.

I cannot link this to any patterns of activity, it just seems to happen sometimes. Restarting the ldm service doesn't work but a reboot of the machine does.

**Comment by LemonBoy** [comment]
This happens when ldmc can't reach ldm, it's very weird since that means something went wrong or ldm has just crashed. Sadly I can't reproduce this locally :(

**Comment by benoliver999** [comment]
I'll keep my eyes peeled for it, it doesn't happen often but when it does, ldm locks out until I reboot.

**Comment by LemonBoy** [comment]
Whenever this happens again try removing the /run/ldm.fifo file and then restart the server, it should start running again with no problem

**Comment by quivocal** [comment]
I'm also experiencing this problem, I'm also running ldm-git on Arch via systemd. For me it happens when I try to unmount the drive with ldmc. ldm -r /dev/sdb1 for example both causes the connect: Connection refused message and also causes ldm to stop automounting any other devices that I plug in. Additionally when I try to unmount the flash drive with the above command it causes the /run/ldm.fifo to be deleted.

**Comment by LemonBoy** [comment]
The latest commit should fix the problem :)

**Comment by benoliver999** [comment]
Good stuff!

Hard to believe yours is the only project that works easily but that appears to be the case! For those of us  nerds without a DE this is a god send.

**Comment by quivocal** [comment]
Great! Tried it out a few times with the newest commit and it seems to work fine. Thanks for fixing it so fast.
